### ISSUE TITLE
License for imported code missing ?

### ISSUE THREAD

**Issue by farhi** [substance33/Spectra#12]
Hello Simon,

I suggest you explicitly mention in the license, or as an external credits/contributions document, that the following code:
- SpecralTools
- FileTools
- MiscTools
- funcs
- load 
- Mtools

were written mostly by me (E. Farhi), from initial work by D. McMorrow and A. Tennant, under a GPL2 license, and hosted at the ILL. I do not maintain this code anymore, this is true, as I develop iFit which is much more advanced.
To be fair, you should similarly mention that spec1d was written initially by by H. Ronnow.

Thanks. 
E. Farhi.

**Comment by farhi** [comment]
And this is also obviously the case for the Optimizers stuff.

OK for collecting code from everywhere, but you should properly credit it, especially when this is my work. It took me years to get it, so please be fair.

**Comment by wardsimon** [comment]
Dear Emmanuel, 

I've created a new file [licencesReadme](https://github.com/simonward86/Spectra/blob/LNS/LicencesReadme) which contains all licence and author information for everything used. The main page has a link to this file and new text explicitly stating that this is a collection of libraries and all information can be found within the aforementioned file.
- SpecralTools
- FileTools
- MiscTools
- Mtools 
  The current SPECTRA was pointing to an old version of the mtools repo. The licensing and credit are in there and I have updated it to be in line with the current ILL mtools version.
  -ResLibCal repository has all the correct information and stating explicitly that it's part of the iFit library. I implemented a new repo as I made a few changes which are out of sync with the iFit version. I hope that this is OK.
  -spec1d: _@spec1d_ is original, but with the same names as previous. The licence file has been changed to reflect that Des _etal_  originally had the idea. Added the Licence/Credit file to the _Criteria_ and _Minimiser_ directories explicitly. This was my fault as the default repo has been merged with the testing repo and the new wrapper function not pushed. The iFit files are very much in testing and have not been documented for use. As such, I hope an explicit update of the licensing and credit is an acceptable response.

If you have any other concerns and can spot anything else which I have forgotten, please let me know. I'll close this if everyone is happy.....

Regards,

S

**Comment by farhi** [comment]
Hi Simon,

many thanks for these additions. BTW, I've now interfaced iFit and SpinW directly, which allows many functionalities from iFit via iFunc models and iData data sets. I'm also designing a replacement for the old 'MFit' stuff, and as you know, iFit is a replacement and extension for spec1d. I look forward to see what you do with all these old tools, but I'm still convinced it would be more efficient to use iFit.

Emmanuel.
