### ISSUE TITLE
problem with spec1d.combine

### ISSUE THREAD

**Issue by tsdev** [substance33/Spectra#6]
Line 120 throws an error if x = [x1 x1 ...], the problem is in line #67, where 
`ind = [1; ceil(cumsum(diff(x(:)))/bin)];`
returns 0 for the second number, and Matlab doesn't accept 0 as index. An addition of eps might be enough, although this can cause a problem for the largest value of x(:):
`ind = [1; ceil(cumsum(diff(x(:)))/bin+eps)];`

**Comment by wardsimon** [comment]
All fixed in latest commit. Added a check x(1) ==x(2) and added eps to x(2) if different. This of course propagates but the addition of eps is 10^-14 will be below both x and toll.
Other bugs have been fixed in the @spec1d/combine function and another method added (LNS branch).
