### ISSUE TITLE
spec1d assumes sorted x-coordinates

### ISSUE THREAD

**Issue by tsdev** [substance33/Spectra#7]
When converting a struct type variable to spec1d, there is no sorting of the x-coordinates, however for example spec1d.plot() assumes sorted x-coordinates. There should be a sorting in one of the functions.

**Comment by wardsimon** [comment]
Added sorting to the creator and loadobj converter. This should fix the problem. However I did originally keep the object unsorted as the user might not want to sort.
Fixed with [commit](https://github.com/simonward86/Spectra/pull/8/commits/2428e64cdbad838cbfffc06cf0e42e259ed5fde6).
